upstream backend_servers {
    least_conn;S
    server backend1:80;
    server backend2:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;

        # IMPORTANT FIX
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
